# LPC313X Platform Support
snd-soc-lpc31xx-objs := lpc31xx-pcm.o
snd-soc-lpc31xx-i2s-objs := lpc31xx-i2s.o

obj-$(CONFIG_SND_LPC313X_SOC) += snd-soc-lpc31xx.o
obj-$(CONFIG_SND_LPC315X_SOC) += snd-soc-lpc31xx.o
obj-$(CONFIG_SND_LPC313X_SOC_I2S) += snd-soc-lpc31xx-i2s.o lpc31xx-i2s-clocking.o

# LPC3XXX Machine Support
snd-soc-ea3131-uda1380-objs := ea3131-uda1380.o

obj-$(CONFIG_SND_EA3131_SOC_I2S_UDA1380) += snd-soc-ea3131-uda1380.o

# LPC315X Machine Support
snd-soc-lpc315x-codec-objs := lpc315x-codec.o

obj-$(CONFIG_SND_LPC315X_SOC_I2S_LPC315X_CODEC) += snd-soc-lpc315x-codec.o

